### ISSUE TITLE
## Pixel 2 XL Android 本地图片显示问题

### ISSUE THREAD

**Issue by snowords** [liangchenhe55/wear-gallery#14]
- [X] 我已确认手机与手表应用版本相同。
- [X] 我已经给予了需要的权限，例如：自启/后台运行/关联唤醒。

**错误描述**
手机端图片不显示

**复现**
每次

**期望的行为**
显示图片

**屏幕截图**
![图片](https://imgur.com/8myLJh0)
![图片](https://imgur.com/1zNFDSL)

**手机（务必填写下列信息）：**
 - 设备：[Pixel 2 XL]
 - 系统：[Android 10]

**手表（务必填写下列信息）：**
 - 设备：[TicWatch C2]
 - 系统：[Wear OS 2.17]
- 应用版本：[ v6.0]

**Comment by liangchenhe55** [comment]
你好 感谢反馈
图片挂掉了哦，是空白界面嘛？
