### ISSUE TITLE
再把表设置成 always on display 这种后 界面的上的时间就不会变

### ISSUE THREAD

**Issue by TheKeyDU** [liangchenhe55/wear-gallery#8]
- [ ] 我已确认手机与手表应用版本相同。
- [ ] 我已经给予了需要的权限，例如：自启/后台运行/关联唤醒。

**错误描述**
对 Bug 简明清晰的描述。

**复现**
如何出现错误：
1. 前往 '...'
2. 点击 '....'

**期望的行为**
简单清晰地描述你期望发生的事情。（程序应当怎样响应）

**屏幕截图**
如果有可能请提供图片。

**手机（务必填写下列信息）：**
 - 设备：[例如三星s9]
 - 系统：[例如 Android P]

**手表（务必填写下列信息）：**
 - 设备：[例如 TicWatchPro]
 - 系统：[例如 Wear OS 2]
- 应用版本：[例如 v5.1.1204]

**其他内容**
可以填写其他额外信息。

**Comment by liangchenhe55** [comment]
抱歉那么晚才回复。最近太忙了。
明天我会尝试复现此问题

**Comment by liangchenhe55** [comment]
经过测试没有复现你反馈的问题。
请确认版本是否大于等于 `5.1.1210`。
先关闭此 Issue，如果你依然有问题请补充详细信息：App版本、设备型号等。
